CREATE USER insa /* DDL ( CREATE ) */
IDENTIFIED BY insa
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 1M ON users;


ALTER USER insa
QUOTA UNLIMITED
ON users;


DROP USER insa CASCADE;


SELECT *
FROM DBA_USERS
WHERE USERNAME IN('INSA', 'HR');


GRANT CREATE SESSION TO insa;
GRANT SELECT ON HR.EMPLOYEES TO insa; /* 객체 권한 부여 */
GRANT SELECT ON HR.DEPARTMENTS TO insa; /* 객체 권한 부여 */


REVOKE CREATE SESSION FROM insa;
REVOKE SELECT ON HR.EMPLOYEES FROM insa;


SELECT *
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'INSA';
