SELECT SQL_ID, SQL_TEXT, PARSE_CALLS, LOADS, EXECUTIONS, PLAN_HASH_VALUE, HASH_VALUE
FROM V$SQL
WHERE SQL_TEXT LIKE '%HR.EMPLOYEES%' AND SQL_TEXT NOT LIKE '%v$sql%';


SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('76vc1dfwz3b1x')); /* SQL_ID ' 76vc1dfwz3b1x ', 실행 계획 ( SQL DEVELOPER 프로그램상 ' F10 ' 키로 확인하는 실행 계획 )*/


ALTER SYSTEM FLUSH SHARED_POOL; /* 메모리 FLUSH */
